### PR TITLE
Drop external folders onto the Tree View to create new project folders

### LINKED ISSUE #480: UX - Cannot drag project folder into tree-view
_From @jsphstls on April 27, 2015 16:6_

**To reproduce:**
Open Atom and clear any project folders or open files.
Open Finder and drag then drop a folder into the Atom tree-view.

**Current result:**
Project folder will not be added to tree-view.

**Expected result:**
Project folder would be added to tree-view.

**Suggested change:**
Allow project folders to be dragged into tree-view.

It is odd that you cannot add a project folder this way since the tree-view is where project folders are navigated. Instead, you can drag a folder into an editor pane, which is where individual files are edited.

_Copied from original issue: atom/atom#6535_

### PR DESCRIPTION
**Pull request by 50Wliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Implements the popularly-requested feature #480.  Basically if no existing folder is selected the Tree View adds the entries in the data transfer event as new project folders.  There are a few rough edges with this implementation, such as but not limited to:
* Folders must be dropped to a blank section of the Tree View _after_ the last entry.  This means that if the Tree View scrolls you will be unable to create a project folder as the entries will get added to the last project.
  * I would like to add support to be able to create project folders when dropping them _between_ project folders, similar to how root drag-and-drop works currently.
* Cannot drag and drop folders onto the Tree View when no Tree View exists.

### Alternate Designs

No alternatives were considered.

### Benefits

External folders can now be dragged-and-dropped into the Tree View to be added as project folders.

### Possible Drawbacks

I don't believe there are any drawbacks with this other than the limitations addressed above.

### Applicable Issues

Fixes #480

### CODE REVIEW

File: lib/tree-view.coffee [hunk 1]
```diff
@@ -1056,6 +1056,9 @@ class TreeView
         # Drop event from OS
         for file in e.dataTransfer.files
           @moveEntry(file.path, newDirectoryPath)
+    else if e.dataTransfer.files.length
```
Comment (liuderchi) [inline lib/tree-view.coffee]: Would `e.dataTransfer.files` be `undefined` ?

Comment (50Wliu) [reply lib/tree-view.coffee]: Good question.  `files` is  standard DataTransfer property that will always be available. https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/files

Comment (liuderchi) [reply lib/tree-view.coffee]: Thanks for the info. Any it says that `dataTransfer` exists on *all drag events*. Good News.

**Comment by 50Wliu** [comment]
I looked into implementing drag-and-drop indicators.  It will be harder than I thought because then you'll have to differentiate between moving external folders _into_ existing projects or whether to create a new project folder for it.  I'll punt that for a later PR.

**Comment by here** [comment]
Note that as of 2018-03-06 , this request remains unreleased in the Atom core editor with the tree-view core package at v221.3 or v222 based on https://github.com/atom/tree-view/releases

**Comment by liuderchi** [comment]
Share a shell snippet for checking releases

```sh
# atom latest releases and corresponding tree-view version
$ curl https://api.github.com/repos/atom/atom/releases/latest -s | grep 'tag_name'

  "tag_name": "v1.24.0",

$ curl https://raw.githubusercontent.com/atom/atom/v1.24.0/package.json -s | grep 'tree-view'

    "tree-view": "0.221.3",
```

**Comment by 50Wliu** [comment]
@here we're dealing with [tree-view spec failures](https://github.com/atom/tree-view/issues/1203) that need to be fixed before we feel comfortable updating it in Atom itself.  Sorry for the delay.
